// Generated by CoffeeScript 1.10.0
(function() {
  var hide;

  hide = (function(_this) {
    return function(container) {
      return container.style.visibility = "hidden";
    };
  })(this);

}).call(this);

//# sourceMappingURL=script.js.map
