name: Build and deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Set up yarn
      run: yarn set version berry

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "yarn-cache-dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.yarn-cache-dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build static
      run: yarn build

    - name: Publish
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: ${{ secrets.TARGET_PATH }}
        strip_components: 1
        overwrite: true
