name: Build and deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --prod
    - name: Build
      run: pnpm build
    - uses: actions/upload-artifact@v4
      with:
        name: 'dist'
        path: 'dist'
        retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: 'dist'
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: ${{ secrets.TARGET_PATH }}
        strip_components: 1
        overwrite: true
